---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latinify
spec:
  selector:
    matchLabels:
      app: latinify
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: latinify
    spec:
      containers:
        - name: latinify
          image: ghcr.io/discite/latinify:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
            name: http
            protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 10M
            limits:
              cpu: 20m
              memory: 20M
---
apiVersion: v1
kind: Service
metadata:  
  name: latinify-service
spec:
  selector:    
    app: latinify
  ports:  
  - name: http
    port: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: latinify-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - latinify.discite.dev
      secretName: latinify-discite-dev-tls
  rules:
  - host: latinify.discite.dev
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: latinify-service
            port: 
              number: 8000
