name: Publish Docker image and Set it on K8s
on:
  push:
    branches: 
     - master
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.LATINIFY_SECRET }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.LATINIFY_SECRET }}
          
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.4.0
        with:
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/${{ github.repository }}:latest
          push: true
  
  push_to_cluster:
    name: Push Docker image to the kubernetes cluster
    needs: [push_to_registry]
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release version number
        id: get_version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: -n romvlvs set image --record deployment/latinify latinify=ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.tag }}
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.19"
        with:
          args: '"-n romvlvs rollout status deployment/latinify"'