name: Publish Docker image
on:
  push:
    branches: 
     - master
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.LATINIFY_SECRET }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.3.0
        with:
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest:latest
          push: true
